### ISSUE TITLE
Issues with usage detection even after container xml is provided

### ISSUE THREAD

**Issue by pkly** [psalm/psalm-plugin-symfony#307] opened 2023-02-25 13:32 UTC
Methods marked with #[Required] as well as class constructors and whole classes (Commands), some services and event subscribers are marked as unused with the `findUnusedCode="true"` setting for psalm.

Class constructors are not marked as used, along with anything using the `#[Required]` attribute, even though it works the same as `@required`.

I had to temporarily disable the unused code search, as this is causing hundreds of issues.

It should be possible to correctly determine usage from the plugin by looking at existing and known references and simply unmarking these issues as needed.

Using the newest version of plugin and psalm as of writing this, php8.2

**Comment by seferov** [comment] 2023-11-10 07:25
@pkly thank you for the report.

The issue is fixed with [v5.0.4](https://github.com/psalm/psalm-plugin-symfony/releases/tag/v5.04). Feel free to reopen the issue if it is not resolved

**Closed as completed by seferov** 2023-11-10 07:25 UTC
