### ISSUE TITLE
QueryBuilderSetParameter: To improve performance set explicit type for objects

### ISSUE THREAD

**Issue by michnovka** [psalm/psalm-plugin-symfony#269] opened 2022-07-22 11:52 UTC
I am using a simple querybuilder with one param:

```php
    public function getInvoiceTransactions(Invoice $invoice): ?array
    {
        $query = $this->createQueryBuilder('t');
        $query->where('t.invoice = :invoice')->setParameter('invoice', $invoice));
        return $query->getQuery()->getResult();
    }
```

This code produces the error
```
QueryBuilderSetParameter: To improve performance set explicit type for objects
```
Changing it to:

```php
        $query->where('t.invoice = :invoice')->setParameter('invoice', $invoice->getId());
```

gets rid of the error.

From the [documentation](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html#binding-parameters-to-your-query):

> Calling `setParameter()` automatically infers which type you are setting as value. This works for integers, arrays of strings/integers, DateTime instances and for managed entities.

Since the invoice in my example is a managed entity, I find the psal error incorrect

**Comment by AndrolGenhald** [comment] 2022-07-22 14:35
This is what is recommended by Doctrine's developers. Duplicate of #158.

**Closed by AndrolGenhald** 2022-07-22 14:35 UTC

**Comment by BenMorel** [comment] 2024-06-27 09:25
> This is what is recommended by Doctrine's developers.

@AndrolGenhald  Do you have a source for this?

The documentation is quite clear:

> This works for integers, arrays of strings/integers, DateTime instances and for managed entities.

So I'm surprised that we have to work around passing managed entities directly (for which, unless I'm mistaken, we cannot provide a type as third parameter?)
